[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "/services"
weight = 2

[[main]]
name = "About"
url = "/about"
weight = 3

[[main]]
name = "Contact"
url = "/contact"
weight = 4

[[footer]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[footer]]
  name = 'Contact'
  pageRef = '/contact'
  weight = 20
